version: "3"
services:
  main-server:
    privileged: true
    build:
      context: ./thumbait
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./thumbait/.env
    ports:
      - 8080:8080
  streamlit-app:
    build:
      context: ./thumbait_frontend
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 5000:5000
